<?php
class ListDataModule extends BaseModule
{
	public $baseTable = 'list_data';
	//模块描述
	public $describe = '名单数据管理';
	//需要控制访问权限的模块方法
    public $actions = Array(
			'index' => '浏览',
			'detailView' => '详情',
			'editView' => '编辑',
			'createView' => '新建',
			'copyView' => '复制',
			'save' => '保存',
			'delete' => '删除',
			'import' => '导入',
			'export' => '导出',
			'modifyFilter' => '编辑过滤',
			);
	//字段定义
	//'字段名'=>Array('UI类型','数据类型','是否强制','提示信息','默认值','最小值/长度','最大值/长度')
	public $fields = Array(
					'license_no'         => Array('5','S',true,'车牌号码','',7,10),
					'license_type'       => Array('20','E',false,'号牌类型','SMALL_CAR'),
					'owner'              => Array('5','S',false,'所有人,姓名/单位名称',''),
					'identify_type'      => Array('20','E',false,'证件类型','IDENTITY_CARD'),
					'identify_no'        => Array('5','S',false,'证件号码',''),
					'telphone'           => Array('3','S',false,'联系固定电话',''),
					'mobile'             => Array('3','S',false,'联系手机',''),
					'address'            => Array('5','S',false,'联系地址',''),
					'buying_price'       => Array('6','N',false,'新车购置价',0,0,999999999),
					'model'              => Array('5','S',false,'品牌型号',''),
					'model_code'         => Array('5','S',false,'型号代码',''),
					'vin_no'             => Array('5','S',true,'车架号/车辆识别号',''),
					'engine_no'          => Array('5','S',false,'发动机号码',''),
					'enroll_date'        => Array('30','D',false,'初登日期',''),
					'seats'              => Array('6','N',false,'核定载客人数',0,0,100),
					'kerb_mass'          => Array('6','N',false,'整备质量(KG)',0,0,9999999),
					'total_mass'         => Array('6','N',false,'总质量(KG)',0,0,9999999),
					'load_mass'          => Array('6','N',false,'核定载重量(KG)',0,0,9999999),
					'tow_mass'           => Array('6','N',false,'核准牵引质量(KG)',0,0,999999),
					'engine'             => Array('6','N',false,'发动机排气量(ML)',0,0,999999),
					'power'              => Array('6','N',false,'发动机功率(KW)',0,0,99999999),
					'origin'             => Array('20','E',false,'产地','DOMESTIC'),
					'run_area'           => Array('20','E',false,'行驶区域','THE_TERRITORY_OF'),					
					'policy_no'          => Array('5','S',false,'保单'),       
                    'insurance_company'  => Array('5','S',false,'保险公司'),     
					'start_date'         => Array('31','DT',false,'生效时间'),	
					'end_date'           => Array('31','DT',false,'终保时间'),       
					'prev_claims'        => Array('6','N',false,'上年出险次数',0,0,999999),
					'current_claims'     => Array('6','N',false,'本年出险次数',0,0,999999),
					'discount'           => Array('6','N',false,'折扣',0,0,999999),       
					'premium'            => Array('6','N',false,'应付保费',0,0,999999),   
					'tvdi'               => Array('6','N',false,'车损险',0,0,999999),       
					'twcdmvi'            => Array('6','N',false,'盗抢险',0,0,999999),       
					'ttbli'              => Array('6','N',false,'三者险',0,0,999999),       
					'tcpli_d'            => Array('6','N',false,'座位险(司机)',0,0,999999),       
					'tcpli_p'            => Array('6','N',false,'座位险(乘客)',0,0,999999),       
					'sloi'               => Array('6','N',false,'自燃险',0,0,999999),       
					'bsdi'               => Array('6','N',false,'划限险',0,0,999999),       
					'bgai'               => Array('6','N',false,'玻璃险',0,0,999999),       
					'nieli'              => Array('6','N',false,'新增设备险',0,0,999999),       
					'vwtli'              => Array('6','N',false,'涉水险',0,0,999999),       
					'stsfs'              => Array('6','N',false,'指定专修',0,0,999999),
					'tvdi_ndsi'          => Array('6','N',false,'不计免赔-车损',0,0,999999),       
					'ttbli_ndsi'         => Array('6','N',false,'不计免赔-三者',0,0,999999),       
					'twcdmvi_ndsi'       => Array('6','N',false,'不计免赔-盗抢',0,0,999999),       
					'tcpli_d_ndsi'       => Array('6','N',false,'不计免赔-座位(司机)',0,0,999999),       
					'tcpli_p_ndsi'       => Array('6','N',false,'不计免赔-座位(乘客)',0,0,999999),       
					'bsdi_ndsi'          => Array('6','N',false,'不计免赔-划限',0,0,999999),       
					'other_ins'          => Array('6','N',false,'其它险种',0,0,999999),
					'batch'              => Array('5','S',true,'批次'),       
					'state'              => Array('20','E',true,'匹配状态'),       
					'request_time'       => Array('31','DT',false,'提交时间'),       
					'respone_time'       => Array('31','DT',false,'响应时间'),
					'logid'              => Array('8','N',false,'日志ID',-1,-10,999999999),
					                     
					'user_attach'        => Array('55','N',true,'归属于',-1),
					'create_time'        => Array('35','DT',true,'创建时间'),					
					'create_userid'      => Array('51','N',true,'创建人'),
					'modify_time'        => Array('36','DT',false,'修改时间'),
					'modify_userid'      => Array('52','N',false,'修改人'),

					);
	//安全字段,可以控制权限
	public $safeFields = Array(
	                'license_no'          ,
	                'license_type'        ,
	                'owner'               ,
	                'identify_type'       ,
	                'identify_no'         ,
	                'telphone'            ,
	                'mobile'              ,
	                'address'             ,
	                'buying_price'        ,
	                'model'               ,
	                'model_code'          ,
	                'vin_no'              ,
	                'engine_no'           ,
	                'enroll_date'         ,
	                'seats'               ,
	                'kerb_mass'           ,
	                'total_mass'          ,
	                'load_mass'           ,
	                'tow_mass'            ,
	                'engine'              ,
	                'power'               ,
	                'origin'              ,
	                'run_area'            ,
	                'policy_no'           ,
	                'insurance_company'   ,
	                'start_date'          ,
	                'end_date'            ,
	                'prev_claims'         ,
	                'current_claims'      ,
					'discount'            ,
					'premium '            ,
					'tvdi'                ,
					'twcdmvi'             ,
					'ttbli'               ,
					'tcpli_d'             ,
					'tcpli_p'             ,
					'sloi'                ,
					'bsdi'                ,
					'bgai'                ,
					'nieli'               ,
					'vwtli'               ,
					'stsfs'               ,
					'tvdi_ndsi'           ,
					'ttbli_ndsi'          ,
					'twcdmvi_ndsi'        ,
					'tcpli_d_ndsi'        ,
					'tcpli_p_ndsi'        ,
					'bsdi_ndsi'           ,
					'other_ins'           ,
					'logid'               ,
					'batch'               ,
					'state'               ,
					'request_time'        ,
					'respone_time'        ,
					'user_attach'         ,
					);
	//列表字段
	public $listFields = Array(
					'vin_no'              ,
	                'license_no'          ,	                
					'batch'               ,
					'state'               ,
					'request_time'        ,
					'respone_time'        ,					
					'policy_no'           ,
	                'insurance_company'   ,
					'premium'             ,
	                'end_date'            ,
					);
	//编辑字段
	public $editFields = Array(
	                'license_no'          ,
	                'license_type'        ,
	                'owner'               ,
	                'identify_type'       ,
	                'identify_no'         ,
	                'telphone'            ,
	                'mobile'              ,
	                'address'             ,
	                'buying_price'        ,
	                'model'               ,
	                'model_code'          ,
	                'vin_no'              ,
	                'engine_no'           ,
	                'enroll_date'         ,
	                'seats'               ,
	                'kerb_mass'           ,
	                'total_mass'          ,
	                'load_mass'           ,
	                'tow_mass'            ,
	                'engine'              ,
	                'power'               ,
	                'origin'              ,
	                'run_area'            ,
	                'policy_no'           ,
	                'insurance_company'   ,
					'premium'             ,
					'discount'            ,
	                'start_date'          ,
	                'end_date'            ,
	                'prev_claims'         ,
	                'current_claims'      ,					
					'premium '            ,
					'tvdi'                ,
					'twcdmvi'             ,
					'ttbli'               ,
					'tcpli_d'             ,
					'tcpli_p'             ,
					'sloi'                ,
					'bsdi'                ,
					'bgai'                ,
					'nieli'               ,
					'vwtli'               ,
					'stsfs'               ,
					'tvdi_ndsi'           ,
					'ttbli_ndsi'          ,
					'twcdmvi_ndsi'        ,
					'tcpli_d_ndsi'        ,
					'tcpli_p_ndsi'        ,
					'bsdi_ndsi'           ,
					'other_ins'           ,
					'batch'               ,
					'state'               ,
					'logid'               ,
					'request_time'        ,
					'respone_time'        ,
					'user_attach'         ,
					);
	//列表最大行数
	public $listMaxRows = 20;
	//可排序字段
	public $orderbyFields = Array(					
                     'license_no',
                     'vin_no',
                     'start_date',
                     'end_date',
                     'batch', 
                     'owner', 
                     'identify_no',  
                     'state',
                     'policy_no',      
                     'request_time',  
                     'respone_time',
                     'insurance_company',
                     'prev_claims',  
                     'current_claims',
                     'enroll_date',
                     'buying_price',
                     'premium',
                     'user_attach',  
                     'create_time',       
                     'create_userid',     
                     'modify_time',       
                     'modify_userid', 
					);
	//默认排序
	public $defaultOrder = Array('create_time','ASC');
	//详情入口字段
	public $enteryField = 'vin_no';
	//详细/编辑视图默认列数
	public $defaultColumns = 3;
	
	//分栏定义
	public $blocks = Array('LBL_AUTO_BASE'=>Array('3',true,Array(
															  'vin_no'                ,
															  'license_no'            ,
															  'license_type'          ,
															  'owner'                 ,
															  'identify_type'         ,
															  'identify_no'           ,
															  'telphone'              ,
															  'mobile'                ,
															  'address'               ,
															  'buying_price'          ,
															  'model'                 ,
															  'model_code'            ,															  
															  'engine_no'             ,
															  'enroll_date'           ,
															  'seats'                 ,
															  'kerb_mass'             ,
															  'total_mass'            ,
															  'load_mass'             ,
															  'tow_mass'              ,
															  'engine'                ,
															  'power'                 ,
															  'origin'                ,
															  'run_area'              ,
											                  )),
						   'LBL_POLICY_INFO'=>Array('3',true,Array(	
															  'policy_no'             ,
															  'insurance_company'     ,
															  'premium'               ,
															  'discount'              ,
															  'start_date'            ,
															  'end_date'              ,
															  'prev_claims'           ,
															  'current_claims'        ,
															  'tvdi'                  ,
															  'twcdmvi'               ,
															  'ttbli'                 ,
															  'tcpli_d'               ,
															  'tcpli_p'               ,
															  'sloi'                  ,
															  'bsdi'                  ,
															  'bgai'                  ,
															  'nieli'                 ,
															  'vwtli'                 ,
															  'stsfs'                 ,
															  'tvdi_ndsi'             ,
															  'ttbli_ndsi'            ,
															  'twcdmvi_ndsi'          ,
															  'tcpli_d_ndsi'          ,
															  'tcpli_p_ndsi'          ,
															  'bsdi_ndsi'             ,
															  'other_ins'             ,		   
						                                      )),	
						   'LBL_MATCH_STATE'=>Array('3',true,Array(
															  'batch'                 ,
															  'state'                 ,															 
															  'request_time'          ,
															  'respone_time'          ,	
																'logid'               ,															  
															 )),
						   'LBL_RECORD_INFO'=>Array('3',true,Array(
															 'user_attach'       ,
															 'create_time'       ,
															 'create_userid'     ,
															 'modify_time'       ,
															 'modify_userid'     ,   
															 )),


															 
						);
						
				
						
						
						
	//枚举字段值
	public $picklist = Array(
		'license_type' => array(
		                'LARGE_AUTOMOBILE'             ,
		                'TRAILER'                      ,
						'SMALL_CAR'                    ,
		                'EMBASSY_CAR'                  ,
		                'CONSULATE_VEHICLE'            ,
		                'HK_MACAO_ENTRY_EXIT_CAR'      ,
		                'COACH_CAR'                    ,
						'POLICE_CAR'                   ,
		                'GENERAL_MOTORCYCLE'           ,
		                'MOPED'                        ,
		                'EMBASSY_MOTORCYCLE'           ,
		                'CONSULATE_MOTORCYCLE'         ,
		                'COACH_MOTORCYCLE'             ,
		                'POLICE_MOTORCYCLE'            ,
		                'TEMPORARY_VEHICLE'            ,		
		                ),
		'identify_type' => array(
						'IDENTITY_CARD'                               ,
						'RESIDENCE_BOOKLET'                           ,
						'PASSPORT'                                    ,
						'MILITARY_DOCUMENTS'                          ,
						'DRIVER_LICENSE'                              ,
						'HOME_CARD'                                   ,
						'HK_IDENTITY_CARD'                            ,
						'WORK_NO'                                     ,
						'TO_TAIWAN_PASS'                              ,
						'HK_MACAO_PASS'                               ,
						'SOLDIER_CARD'                                ,
						'HK_MACAO_RESIDENTS_TRAVELING_MAINLAND_PASSES',
						'TAIWAN_RESIDENTS_TRAVELING_MAINLAND_PASSES'  ,
						'ORGANIZATION_CODE_CERTIFICATE'               ,
						'OTHER'                                       ,		
						),
		'state'  => array(
						'WAITING',
						'WAIT_RESPONE',
						'MATCH_PART',
						'FAILURE',
						'SUCCESS',	
						),
		'origin' => Array(
							'DOMESTIC',
							'IMPORTED',
							'JOINT_VENTURE'
							),
		'run_area' => array(
							'THE_PROVINCE',
							'THE_TERRITORY_OF',
							'THE_FIXED_LINE',
							'THE_FLOOR',
							),

							
	);
	
	//字段关联
	public $associateTo = Array(
		'user_attach' => Array('MODULE','User','detailView','id','user_name'),		
        'create_userid' => Array('MODULE','User','detailView','id','user_name'),		
		'modify_userid' => Array('MODULE','User','detailView','id','user_name'),
	    //'task_id'    => Array('MODULE','MatchTask','detailView','id','name'),		
	);
	
	//模块关联
	public $associateBy = Array(

	);
	//记录权限关联字段名
	public $shareField = 'user_attach';	
	
	//允许批量修改字段		
	public $batchEditFields = Array(
				'batch'                     ,
				'state'                     ,
				'logid'                     ,
				'user_attach'               ,		
	
	);	

	//允许miss编辑字段
	public $missEditFields = Array(
	                'license_no'          ,
	                'license_type'        ,
	                'owner'               ,
	                'identify_type'       ,
	                'identify_no'         ,
	                'telphone'            ,
	                'mobile'              ,
	                'address'             ,
	                'buying_price'        ,
	                'model'               ,
	                'model_code'          ,
	                'vin_no'              ,
	                'engine_no'           ,
	                'enroll_date'         ,
	                'seats'               ,
	                'kerb_mass'           ,
	                'total_mass'          ,
	                'load_mass'           ,
	                'tow_mass'            ,
	                'engine'              ,
	                'power'               ,
	                'origin'              ,
	                'run_area'            ,
	                'policy_no'           ,
	                'insurance_company'   ,
	                'start_date'          ,
	                'end_date'            ,
	                'prev_claims'         ,
	                'current_claims'      ,
					'discount'            ,
					'premium '            ,
					'tvdi'                ,
					'twcdmvi'             ,
					'ttbli'               ,
					'tcpli_d'             ,
					'tcpli_p'             ,
					'sloi'                ,
					'bsdi'                ,
					'bgai'                ,
					'nieli'               ,
					'vwtli'               ,
					'stsfs'               ,
					'tvdi_ndsi'           ,
					'ttbli_ndsi'          ,
					'twcdmvi_ndsi'        ,
					'tcpli_d_ndsi'        ,
					'tcpli_p_ndsi'        ,
					'bsdi_ndsi'           ,
					'other_ins'           ,
					'batch'               ,
					'state'               ,
					'request_time'        ,
					'respone_time'        ,
					'user_attach'         ,
	
	);
};



?>